spring.application.name=RightDigitsFunctionalProgrammingMicroService
spring.jpa.properties.hibernate.connection.release_mode=auto
#$spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy